2018-04-14 00:33:22,968 ERROR 76098 [-/::1/-/6ms GET /] nodejs.Template render error: Error: template not found: /Users/why/iDreamFia/www.xiaobaiparty.com/app/_layout.tpl
    at Object._prettifyError (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/nunjucks/src/lib.js:35:11)
    at /Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/nunjucks/src/environment.js:547:19
    at eval (eval at _compile (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/nunjucks/src/environment.js:617:18), <anonymous>:10:11)
    at createTemplate (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/nunjucks/src/environment.js:279:11)
    at next (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/nunjucks/src/lib.js:283:7)
    at handle (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/nunjucks/src/environment.js:313:11)
    at /Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/nunjucks/src/environment.js:323:9
    at next (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/nunjucks/src/lib.js:281:7)
    at Object.asyncIter (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/nunjucks/src/lib.js:287:3)
    at NunjucksEnvironment.getTemplate (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/nunjucks/src/environment.js:305:9)
name: 'Template render error'
pid: 76098
hostname: whydeMacBook-Pro.local

2018-04-14 00:34:19,712 ERROR 76098 [-/::1/-/2ms GET /] nodejs.Template render error: Error: template not found: /Users/why/iDreamFia/www.xiaobaiparty.com/app/view/_layout.tpl
    at Object._prettifyError (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/nunjucks/src/lib.js:35:11)
    at /Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/nunjucks/src/environment.js:547:19
    at eval (eval at _compile (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/nunjucks/src/environment.js:617:18), <anonymous>:10:11)
    at createTemplate (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/nunjucks/src/environment.js:279:11)
    at next (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/nunjucks/src/lib.js:283:7)
    at handle (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/nunjucks/src/environment.js:313:11)
    at /Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/nunjucks/src/environment.js:323:9
    at next (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/nunjucks/src/lib.js:281:7)
    at Object.asyncIter (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/nunjucks/src/lib.js:287:3)
    at NunjucksEnvironment.getTemplate (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/nunjucks/src/environment.js:305:9)
name: 'Template render error'
pid: 76098
hostname: whydeMacBook-Pro.local

2018-04-14 00:34:22,025 ERROR 76098 [-/::1/-/3ms GET /] nodejs.Template render error: Error: template not found: /Users/why/iDreamFia/www.xiaobaiparty.com/app/view/_layout.tpl
    at Object._prettifyError (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/nunjucks/src/lib.js:35:11)
    at /Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/nunjucks/src/environment.js:547:19
    at eval (eval at _compile (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/nunjucks/src/environment.js:617:18), <anonymous>:10:11)
    at createTemplate (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/nunjucks/src/environment.js:279:11)
    at next (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/nunjucks/src/lib.js:283:7)
    at handle (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/nunjucks/src/environment.js:313:11)
    at /Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/nunjucks/src/environment.js:323:9
    at next (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/nunjucks/src/lib.js:281:7)
    at Object.asyncIter (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/nunjucks/src/lib.js:287:3)
    at NunjucksEnvironment.getTemplate (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/nunjucks/src/environment.js:305:9)
name: 'Template render error'
pid: 76098
hostname: whydeMacBook-Pro.local

2018-04-14 00:34:23,327 ERROR 76098 [-/::1/-/2ms GET /] nodejs.Template render error: Error: template not found: /Users/why/iDreamFia/www.xiaobaiparty.com/app/view/_layout.tpl
    at Object._prettifyError (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/nunjucks/src/lib.js:35:11)
    at /Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/nunjucks/src/environment.js:547:19
    at eval (eval at _compile (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/nunjucks/src/environment.js:617:18), <anonymous>:10:11)
    at createTemplate (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/nunjucks/src/environment.js:279:11)
    at next (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/nunjucks/src/lib.js:283:7)
    at handle (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/nunjucks/src/environment.js:313:11)
    at /Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/nunjucks/src/environment.js:323:9
    at next (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/nunjucks/src/lib.js:281:7)
    at Object.asyncIter (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/nunjucks/src/lib.js:287:3)
    at NunjucksEnvironment.getTemplate (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/nunjucks/src/environment.js:305:9)
name: 'Template render error'
pid: 76098
hostname: whydeMacBook-Pro.local

2018-04-14 02:34:24,965 ERROR 76461 nodejs.ClusterClientNoResponseError: client no response in 5601661ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 76461
hostname: whydeMacBook-Pro.local

2018-04-14 05:49:20,421 ERROR 76461 nodejs.ClusterClientNoResponseError: client no response in 11695423ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 76461
hostname: whydeMacBook-Pro.local

2018-04-14 07:37:24,428 ERROR 76461 nodejs.ClusterClientNoResponseError: client no response in 6483527ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 76461
hostname: whydeMacBook-Pro.local

2018-04-14 09:25:28,450 ERROR 76461 nodejs.ClusterClientNoResponseError: client no response in 6483721ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 76461
hostname: whydeMacBook-Pro.local

2018-04-14 10:07:14,480 ERROR 76461 nodejs.ClusterClientNoResponseError: client no response in 2505748ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 76461
hostname: whydeMacBook-Pro.local

2018-04-14 12:07:14,007 ERROR 76461 nodejs.ClusterClientNoResponseError: client no response in 238330ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 76461
hostname: whydeMacBook-Pro.local

2018-04-14 13:58:20,154 ERROR 76461 nodejs.ClusterClientNoResponseError: client no response in 85251ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 76461
hostname: whydeMacBook-Pro.local

2018-04-14 14:44:57,438 ERROR 76461 nodejs.ClusterClientNoResponseError: client no response in 2797269ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 76461
hostname: whydeMacBook-Pro.local

2018-04-14 16:41:24,797 ERROR 76461 nodejs.ClusterClientNoResponseError: client no response in 6987355ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 76461
hostname: whydeMacBook-Pro.local

2018-04-14 16:45:14,098 ERROR 76461 nodejs.ClusterClientNoResponseError: client no response in 209283ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 76461
hostname: whydeMacBook-Pro.local

2018-04-14 17:45:46,232 ERROR 76461 nodejs.ClusterClientNoResponseError: client no response in 3612114ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 76461
hostname: whydeMacBook-Pro.local

2018-04-14 18:47:18,109 ERROR 76461 nodejs.ClusterClientNoResponseError: client no response in 3611837ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 76461
hostname: whydeMacBook-Pro.local

2018-04-14 19:10:38,034 ERROR 76461 nodejs.ClusterClientNoResponseError: client no response in 1359908ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 76461
hostname: whydeMacBook-Pro.local

2018-04-14 19:11:47,668 ERROR 76461 nodejs.ClusterClientNoResponseError: client no response in 69633ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 76461
hostname: whydeMacBook-Pro.local

2018-04-14 23:21:14,497 ERROR 76461 nodejs.ClusterClientNoResponseError: client no response in 4203340ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 76461
hostname: whydeMacBook-Pro.local

2018-04-14 23:28:23,752 ERROR 76461 nodejs.ClusterClientNoResponseError: client no response in 129177ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 76461
hostname: whydeMacBook-Pro.local

2018-04-15 01:17:02,700 ERROR 76461 nodejs.ClusterClientNoResponseError: client no response in 6238878ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 76461
hostname: whydeMacBook-Pro.local

2018-04-15 04:21:17,572 ERROR 76461 nodejs.ClusterClientNoResponseError: client no response in 11054534ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 76461
hostname: whydeMacBook-Pro.local

2018-04-15 06:09:21,400 ERROR 76461 nodejs.ClusterClientNoResponseError: client no response in 6483628ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 76461
hostname: whydeMacBook-Pro.local

2018-04-15 07:57:25,438 ERROR 76461 nodejs.ClusterClientNoResponseError: client no response in 6483925ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 76461
hostname: whydeMacBook-Pro.local

2018-04-15 09:45:30,403 ERROR 76461 nodejs.ClusterClientNoResponseError: client no response in 6484828ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 76461
hostname: whydeMacBook-Pro.local

2018-04-15 10:56:48,421 ERROR 76461 nodejs.ClusterClientNoResponseError: client no response in 4277783ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 76461
hostname: whydeMacBook-Pro.local

2018-04-15 11:57:40,867 ERROR 76461 nodejs.ClusterClientNoResponseError: client no response in 3612417ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 76461
hostname: whydeMacBook-Pro.local

2018-04-15 12:58:32,665 ERROR 76461 nodejs.ClusterClientNoResponseError: client no response in 3611782ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 76461
hostname: whydeMacBook-Pro.local

2018-04-15 13:12:12,078 ERROR 76461 nodejs.ClusterClientNoResponseError: client no response in 779399ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 76461
hostname: whydeMacBook-Pro.local

2018-04-15 13:14:58,736 ERROR 76461 nodejs.ClusterClientNoResponseError: client no response in 166649ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 76461
hostname: whydeMacBook-Pro.local

2018-04-15 17:19:04,326 ERROR 76461 nodejs.ClusterClientNoResponseError: client no response in 1242128ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 76461
hostname: whydeMacBook-Pro.local

2018-04-15 17:40:41,839 ERROR 76461 nodejs.ClusterClientNoResponseError: client no response in 997450ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 76461
hostname: whydeMacBook-Pro.local

2018-04-15 20:34:51,568 ERROR 76461 nodejs.ClusterClientNoResponseError: client no response in 10349683ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 76461
hostname: whydeMacBook-Pro.local

2018-04-16 19:57:20,127 ERROR 84733 nodejs.ClusterClientNoResponseError: client no response in 2660694ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 84733
hostname: whydeMacBook-Pro.local

2018-04-16 20:22:23,552 ERROR 84733 nodejs.ClusterClientNoResponseError: client no response in 1483408ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 84733
hostname: whydeMacBook-Pro.local

2018-04-16 21:06:38,073 ERROR 84733 nodejs.ClusterClientNoResponseError: client no response in 185667ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 84733
hostname: whydeMacBook-Pro.local

2018-04-16 22:38:59,537 ERROR 84733 nodejs.ClusterClientNoResponseError: client no response in 580669ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 84733
hostname: whydeMacBook-Pro.local

2018-04-16 23:45:55,105 ERROR 84733 nodejs.ClusterClientNoResponseError: client no response in 1095058ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 84733
hostname: whydeMacBook-Pro.local

2018-04-17 01:34:02,310 ERROR 84733 nodejs.ClusterClientNoResponseError: client no response in 6467189ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 84733
hostname: whydeMacBook-Pro.local

2018-04-17 04:34:30,415 ERROR 84733 nodejs.ClusterClientNoResponseError: client no response in 10828010ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 84733
hostname: whydeMacBook-Pro.local

2018-04-17 06:22:34,816 ERROR 84733 nodejs.ClusterClientNoResponseError: client no response in 6484222ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 84733
hostname: whydeMacBook-Pro.local

2018-04-17 06:34:35,825 ERROR 84733 nodejs.ClusterClientNoResponseError: client no response in 680980ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/why/iDreamFia/www.xiaobaiparty.com/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 84733
hostname: whydeMacBook-Pro.local

